### ISSUE TITLE
Fix projection of DC

### ISSUE THREAD

**Issue by eschow** [DCActionforChildren/dcaction#10]

**Comment by ajschumacher** [comment]
What's wrong with the projection of DC? @eschow?

**Comment by eschow** [comment]
The north end of DC isn't pointing north. Cartographers I've worked insist on a different projection when we're only displaying DC. From my experience, if it's print, we go with some Maryland/VA specific projection but online it's the standard google projection. 

The way it displays on our map now, it just feels like everything is skewed and distorted. Not square like we're used to!

Hope that clarifies.

**Comment by ajschumacher** [comment]
Wow! I totally didn't notice that until you pointed it out - thanks! I switched it to a mercator projection and I think it looks a lot better as far as pointing in the right direction; take a look and let me know if I'm wrong about that. Also there's a nicer way of centering and zooming:

projection = d3.geo.mercator()
  .center([-77.01551, 38.90755]) // Dunbar High School
  .scale(150000)
  .translate([width/2, height/2]);
