### ISSUE TITLE
Repo is missing licence

### ISSUE THREAD

**Issue by andylolz** [DCActionforChildren/dcaction#103]
I could pull request the MIT licence in here, but that seems a bit presumptuous!

Still, I’m sure NE Child Poverty commission ([with whom we made this](https://github.com/DataKind-UK/child-poverty-commission-dashboard)) would really appreciate a permissive licence on your original work.

Thanks very much for building this awesome thing!

**Comment by nickmcclellan** [comment]
Hey Andy, I'm just a little foggy on this. Are you saying we should add something like a Creative Commons license? You're not being presumptuous, we definitely would like to have this work adapted and built upon. I will chat with our team and put the appropriate license on the page. Thanks for reaching out!

**Comment by andylolz** [comment]
> Are you saying we should add something like a Creative Commons license?

Exactly! But Creative Commons [isn’t recommended for code](https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F).

There’s a good (github) website for choosing a licence here:
http://choosealicense.com

Then the norm is to create a file in the root called LICENSE with the licence text.

**Comment by andylolz** [comment]
Did you mean to close this one, @nickmcclellan?

**Comment by pdarche** [comment]
Hey @nickmcclellan and @andylolz, just checked in with @hyesookchung and the MIT license works.  Nick, I'm going to reopen the issue.  Can you either add that license or have Andy submit a pull request?  Either way, we need to make sure DC Action for Children is indicated as copyright holder.

**Comment by andylolz** [comment]
Pull request sent :)
