### ISSUE TITLE
Urgent fixes 

### ISSUE THREAD

**Issue by shanab202** [DCActionforChildren/dcaction#108]
Hi everyone,

A few issues have popped up that we need resolved ASAP. We are rolling out the Tool and promoting with key stakeholders (government officials, advocates, and media) around town. I understand that some of these may be quicker to resolve than others, so please let us know what can be done quickly. Our next meeting is October 28th.

-Improve view of the map by decreasing font size of text ("Where resources and well-being vary in DC") and removing indicator "buttons" (aka four key policy insights:children in poverty, children in single mother families, reading and math proficiency). 

-Change neighborhood asset layers so that values that = 0 appear gray on the map. For example, libraries currently appear as 1 or less or 2 or more on the map—very misleading since many neighborhoods don’t have libraries. I know the computer creates the legends on its own--maybe we can fix this by leaving the value blank or putting n/a in the file. (Similar to how infant/toddler child care capacity)

-Cleaning up existing school point-based data— not all schools have complete information. Is this something that we need to do on our end? Checked the google spreadsheet and it looks complete. Did I miss something? 

Thanks for all of your help! Please let me know if anything is unclear.

**Comment by ShubhaBala** [comment]
Hi all!

I think I've met most of you... Just a heads up that as DataKind helps make
sure these things get fixed please do let me know if you're able to take
any of these critical and useful fixes on!  I want to ensure no double work
gets done and that everything is complete in this tight timeline!

Also some of you may hear from me individually.

Thanks!

On Thursday, October 16, 2014, shanab202 notifications@github.com wrote:

> Hi everyone,
> 
> A few issues have popped up that we need resolved ASAP. We are rolling out
> the Tool and promoting with key stakeholders (government officials,
> advocates, and media) around town. I understand that some of these may be
> quicker to resolve than others, so please let us know what can be done
> quickly. Our next meeting is October 28th.
> 
> -Improve view of the map by decreasing font size of text ("Where resources
> and well-being vary in DC") and removing indicator "buttons" (aka four key
> policy insights:children in poverty, children in single mother families,
> reading and math proficiency).
> 
> -Change neighborhood asset layers so that values that = 0 appear gray on
> the map. For example, libraries currently appear as 1 or less or 2 or more
> on the map—very misleading since many neighborhoods don’t have libraries. I
> know the computer creates the legends on its own--maybe we can fix this by
> leaving the value blank or putting n/a in the file. (Similar to how
> infant/toddler child care capacity)
> 
> -Cleaning up existing school point-based data— not all schools have
> complete information. Is this something that we need to do on our end?
> Checked the google spreadsheet and it looks complete. Did I miss something?
> 
> Thanks for all of your help! Please let me know if anything is unclear.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DCActionforChildren/dcaction/issues/108.

## 

_DataKind http://www.datakind.org/_
Shubha Bala
Programs Strategist
shubha@datakind.org

Follow us on Twitter @DataKind https://twitter.com/DataKind
Get involved and stay in touch http://www.datakind.org/getinvolved/!
Join our NYC Meetup http://www.meetup.com/DataKind-NYC/!

**Comment by charlesdguthrie** [comment]
I wish I could help, but since the beginning of this project I've started a
Master's program in Data Science at NYU part-time and it takes up all my
free time!

**Comment by eschow** [comment]
I'm slammed with a project at work for the rest of the weekend/week so I'm not certain I can be of much help. Sorry!

**Comment by ShubhaBala** [comment]
Hi @shanab202 

Can you give us an example of a school that is not showing complete information?

Thanks!

**Comment by pdarche** [comment]
@shanab202, we found some problematic but it looks like the data is missing from the source files.  Which google spreadsheet?  Also, @nickmcclellan where are the school files (schools.csv/json, charters.csv/json) derived from?  Is it possible that the source data has been updated but the files used by the app weren't updated?

**Comment by shanab202** [comment]
@pdarche here is the link to the google spreadsheet. I thought this was the school data store. Do we need to connect this to the school source files? 

https://docs.google.com/spreadsheets/d/1ZHTM7qr1DQumVAVslGNf_A1OJkqyGXRZUK-8rDT_4Qk/edit?usp=sharing

**Comment by craigbarowsky** [comment]
I would like to close this issue as I have opened 5 separate issues to account for the updates we are hoping to fix by the 28th.  Please comment about each item in the appropriate new threads.  Thanks!

**Comment by shanab202** [comment]
Thanks @craigbarowsky!
