### ISSUE TITLE
Display Median Income

### ISSUE THREAD

**Issue by craigbarowsky** [DCActionforChildren/dcaction#113]
Shana is going to add a disclaimer about how the median is being calculated but they have asked that we have this appear.  I am hoping to have Pete add more details to this to make sure it's clear what we are hoping to see here.

**Comment by pdarche** [comment]
See #56 for more information and discussion about this issue.  HyeSook and Shana would like to use their weighted average approach to calculate the statistic.  Details of their approach are in the footnotes here: http://datacenter.kidscount.org/data/tables/7396-median-income-of-families-with-children-by-neighborhood?loc=10&loct=3#detailed/3/any/false/971/3608,3490,3566,3567,3568,3569,3570,3571,3572,3573,3574,3575,3576,3577,3578,3579,3580,3581,3582,3583,3584,3585,3586,3587,3588,3589,3590,3591,3592,3593,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603,3604/14478

@jotok, it looks like the this statistic is being computed in the data/crosswalk.rb file and that median income currently being averaged.  How difficult would it be to update the script to match the approach DC Action is using in their reporting?

**Comment by jotok** [comment]
So I was going to say that we should be able to do this using a ratio of ACS variables, but now that I look at `fetch_acs.rb` I see that it's being calculated as a ratio already. Can someone check to see what the ACS variables B09002_015E and B09002_001E are? We might already have what we need.

**Comment by pdarche** [comment]
Hey @jotok, below is what I found about the variables.  Looks like the vars you asked about are about the number number of children under 18 by family type and age.  Included as well are some median  income vars.  Info from [here](http://proximityone.com/apigateway_acs5year.htm).  Also and unfortunately, we'd like to resolve this issue by Tuesday morning.  I know this is ridiculously short notice but any help you could provide around this is greatly appreciated.  Thanks so much!!!!

_.B09002. Own Children Under 18 Years by Family Type and Age
.Universe: Own children under 18 years_
 B09002_001E     Total
 B09002_015E     Female householder, no husband present:

_.B19013. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars)
  .Universe: Households_
- B19013_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013A. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (White Alone Householder)
  .Universe: Households with a householder who is White alone
- B19013A_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013B. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (Black or African American A
  .Universe: Households with a householder who is Black or African American alone
- B19013B_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013C. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (American Indian and Alaska
  .Universe: Households with a householder who is American Indian and Alaska Native alone
- B19013C_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013D. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (Asian Alone Householder)
  .Universe: Households with a householder who is Asian alone
- B19013D_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013E. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (Native Hawaiian and Other P
  .Universe: Households with a householder who is Native Hawaiian and Other Pacific Islander alone
- B19013E_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013F. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (Some Other Race Alone House
  .Universe: Households with a householder who is Some other race alone
- B19013F_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013G. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (Two or More Races Household
  .Universe: Households with a householder who is Two or more races
- B19013G_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013H. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (White Alone, Not Hispanic O
  .Universe: Households with a householder who is White alone, not Hispanic or Latino
- B19013H_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19013I. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) (Hispanic or Latino Househol
  .Universe: Households with a householder who is Hispanic or Latino
- B19013I_001E     Median household income in the past 12 months (in 2010 inflation-adjusted dollars)
  .B19019. Median Household Income in the Past 12 Months (In 2010 Inflation-Adjusted Dollars) by Household Size

**Comment by pdarche** [comment]
Hey @jotok as far as I can tell the median_family_income figure is the only field being averaged but I'm confused about the tract_total_weight that it's being divided by.  Is the tract weight just a sum of the portions (the values of the tracts belonging to the nbhd)?  If I'm not mistaken, all of the values are being weighted by the portion of the tract within the cluster in the nbhd value loop (starting on line 71) and then turned into a ratios (divided by the sum of the culster's tracts \* portions) by loop starting on line 93.  Isn't that ratio exactly what we want?

**Comment by pdarche** [comment]
@shanab202 is the data that you've reported [here](http://datacenter.kidscount.org/data/tables/7396-median-income-of-families-with-children-by-neighborhood?loc=10&loct=3#detailed/3/any/false/971/3608,3490,3566,3567,3568,3569,3570,3571,3572,3573,3574,3575,3576,3577,3578,3579,3580,3581,3582,3583,3584,3585,3586,3587,3588,3589,3590,3591,3592,3593,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603,3604/14478) the most up-to-date data / the data you'd want to see on the map?  I'd like to use it to compare to with the output of the modified script code.  Also, @nickmcclellan, if the data is the latest I might just go in and hand-replace the values in the csv.  How long would it be to re-add the median income functionality in the map once the data is in place?  Would it be possible to just use the median income data that's there now to create a branch that includes the functionality and we can just merge it when the new data is in there?  Let me know and thanks again!

**Comment by shanab202** [comment]
@pdarche that's a great question. That is not the most up-to-date data. I believe the 2012 ACS has more updated values at the census tract level. We haven't updated this indicator in some time and we really need to. If necessary, we can use the 2010 census data included in our Data Center(the link in your comment above), but it would be ideal to use the ACS data to provide the most timely information. Thank you all so much!

**Comment by jotok** [comment]
The KidsCount website says that they compute a weighted average of medians using the number of families who reported median income. It looks like I can use B19119_001E as the median income variable, but I can't find "number of families" as an ACS variable. If someone can help me find this, I can complete the data task for this issue. Also, someone should double check that B19119_001E looks like the correct median income variable.

I'm in and out of meetings all day, but I'll try to handle this quickly if we can find the right code.

**Comment by jotok** [comment]
Hmm, I guess it's just "Total housing units" B00002_001E. OK, I'm going to create a variable that's a weighted sum of B19119_001E \* B00002_001E in the numerator (where the weights come from the tract-neighborhood crosswalk) and a wighted sum of B00002_001E in the denominator.

**Comment by pdarche** [comment]
Thanks, @shanab202 and @jotok!  Josh, I'll look into the variables and try to find the number of families.  Shana, do you, perchance, know which ACS variable that is?  Also, @nickmcclellan, I'm also going to update the data with DC Action's 2010 numbers.  Could you reimplement the html and js to get the data showing on the map again?  I'm planning on having the data updated by 4pm today.  If Josh is able to update the script this morning then we can just use those new numbers and if not then we'll just use the hand-inputted numbers.

**Comment by nickmcclellan** [comment]
I'm happy to edit the HTML to get this on the map.

**Comment by shanab202** [comment]
@jotok @pdarche thanks for looking into this! It's fine to use number of housing units. We can update the methodology accordingly.

**Comment by pdarche** [comment]
Great!  Thanks @shanab202!  @jotok it looks like ACS just has households and then subfamilies within households.  I guess you can count the total subfamilies, but as long as households works, then let's just stick with that!  Also, 2012 ACS definitions are [here](http://www.census.gov/acs/www/Downloads/data_documentation/SubjectDefinitions/2012_ACSSubjectDefinitions.pdf) and if you search for 'subfamily' it'll take you to the section.

**Comment by jotok** [comment]
I've issued a pull request, can someone QA the numbers to see if they look right?

**Comment by pdarche** [comment]
Great!  Thanks, @jotok.  I'm going to take a look but @nickmcclellan, would you mind checking it out as well and @shanab202 could you give a final sign-off?

**Comment by pdarche** [comment]
The numbers seem to align pretty well with those from DCA's 2010 report though I'll let @shanab202  give the final thumbs up.  @nickmcclellan, what steps are needed to transform this data into the final neighborhoods.csv / neighborhoods44.json files?

**Comment by shanab202** [comment]
Happy to take a look-- what's the best way to that? Sorry--still building my github skills. @pdarche

**Comment by jotok** [comment]
The easiest thing is probably just to download the newly generated CSV:
https://raw.githubusercontent.com/jotok/dcaction/gh-pages/data/acs_nbhd_data
.

median_family_income is the last column in the spreadhseet (column LB).

**Comment by jotok** [comment]
Sorry, chopped of the extension:
https://raw.githubusercontent.com/jotok/dcaction/gh-pages/data/acs_nbhd_data.csv

**Comment by shanab202** [comment]
Thanks @jotok! Just reviewed-- the numbers look like good approximations. Thanks for being so responsive! We are so grateful!!!

**Comment by pdarche** [comment]
@jotok yes, thanks!  I'll merge in the pull request.  We now just need to roll that into the data used by the map and re-add the markup and js to show that indicator, which Nick is on.

**Comment by pdarche** [comment]
Sorry! re-opening until the the map is update.

**Comment by craigbarowsky** [comment]
Thanks everyone on getting this finalized.  @nickmcclellan let us know when you've had a chance to add the new data into the tool.

**Comment by pdarche** [comment]
THANKS NICK!

On Mon, Oct 27, 2014 at 9:07 PM, nickmcclellan notifications@github.com
wrote:

> Closed #113 https://github.com/DCActionforChildren/dcaction/issues/113
> via ffb959d
> https://github.com/DCActionforChildren/dcaction/commit/ffb959db77ba0ae0a43f479cad4dc16bd29817ba
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DCActionforChildren/dcaction/issues/113#event-184436026
> .

## 

Peter Darche
(415) 595-2940

**Comment by shanab202** [comment]
@nickmcclellan @jotok @pdarche THANK YOU ALL!!! So awesome!!!
