### ISSUE TITLE
Clean up choropleth layer swapping code

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#12]
dc.html provides for basic layer switching for DC choropleth maps, but the code needs to be simplified. There needs to be an array that defines each layer and threshold. The map needs to toggle between these maps based on a key term to identify each layer.

**Comment by ajschumacher** [comment]
I tweaked this a little bit, but haven't fully generalized it; still using the manually entered color breakpoints etc.

**Comment by eschow** [comment]
The code now looks at the html id of the list item and dynamically changes the domain/scale. Same situation with the circle animations as well.

See: https://github.com/nickmcclellan/dcaction/commit/97c19f85000934d51017604b4bb8a6e64c2e0b47
