### ISSUE TITLE
Update summaries hardcoded in index.html and index2.html

### ISSUE THREAD

**Issue by joshdelarosa1** [DCActionforChildren/dcaction#121]
On the initial load, citywide data is presented.  The city wide data is not in the neighborhood.csv, it is hardcoded in index.html and index2.html.

I suspect the following variables are hardcoded:

Population total
Population under 18
Single mother families
Children in poverty
NonHispanic White (total)
NonHispanic Black (total)
NonHispanic Other (total)
Hispanic (total)
NonHispanic White (under 18)
NonHispanic Black (under 18)
NonHispanic Other (under 18)
Hispanic (under 18)

With the update from 2012 to 2013 ACS data, the citywide summarizes need to be updated.

I creating a citywide version of the tract  fetch_acs.rb program.
Next, to create citywide data, change the geography to GEO = 'for=state:11'.
There is no need to crosswalk city data as we want the citywide data displayed.

Use the new output to update index.html and index2.html

**Comment by ajschumacher** [comment]
#127 duplicates this one, but has a little more context, so closing this one
