### ISSUE TITLE
decomplect documentation

### ISSUE THREAD

**Issue by ajschumacher** [DCActionforChildren/dcaction#124]
The repo `README.md` is super stale, and there's real documentation off at this Google Doc: https://docs.google.com/document/d/1u9yJ1yJt6T4jOb_EUN6aXn-ugzuRCiNVmvRz19_k9cs/edit Better to have documentation in fewer places; recommend putting the google doc contents into the README.md.

**Comment by mjrich** [comment]
+1

**Comment by ajschumacher** [comment]
possible addition, from Josh De La Rosa's email:

> Also, if I can, tomorrow I’ll take a look at the changes (http://www.census.gov/acs/www/data_documentation/2013_data_product_changes/) that may impact our program.

**Comment by ajschumacher** [comment]
process note from @jotok's email:

> I made the change to the API URL in `fetch_acs.rb`, and everything appears
> to have run without a hitch. `acs_tract_data.json` and `acs_nbhd_data.csv`
> should now contain updated data.

**Comment by ajschumacher** [comment]
notes from @mjrich's email:

> 1. Thanks to the Joshs and others great work, updating the tool and data is a cinch.  This is not an accident, and was a core part of v2 for this very reason.  Nice work!
> 2. The main thing we need to do is match-up variable names from ACS to current neighborhoods.csv file powering the visualization.  I'm 99% of the way there after a few hours tonight, but would be great if you Shana/HyeSook can verify and correct in this spreadsheet (which I've tried to color-code and self-document as best I can here): https://docs.google.com/spreadsheet/ccc?key=0AliQRBwTvad9dHpVQkltc05MS2FzdGpCRFZSb0djdFE#gid=35
> 3. Once all those variable names are confirmed and calculated, we can export a new CSV, replace the current neighborhoods.csv, first locally to test and then on the main hosting server, and everything should (fingers crossed) be updated.
> 4. To make this easier in the future, I've documented some steps and thoughts here: https://docs.google.com/document/d/1u9yJ1yJt6T4jOb_EUN6aXn-ugzuRCiNVmvRz19_k9cs/edit

**Comment by ajschumacher** [comment]
good ideas from @jotok:

> Is this something we could simplify by having the script output the same
> variable names that the front-end code is expecting? It would be an easy
> change!
> 
> While we're documenting the process, we should keep an eye out for other
> steps that could be automated. Less time fussing with spreadsheets means
> more time for cool visualizations and policy proposals.

(moved this to #126)

**Comment by ajschumacher** [comment]
I'm working on this right now:
- cleaning out `README.md`
- moving in the documentation from https://docs.google.com/document/d/1u9yJ1yJt6T4jOb_EUN6aXn-ugzuRCiNVmvRz19_k9cs/edit

(I may end up splitting out the other things that have appeared here to a new issue so that I can close this issue after completing its original intent.)

**Comment by ajschumacher** [comment]
oh btw that abandoned the trello; I'm pretty sure I was the only one who ever really thought the trello was a good idea

**Comment by ajschumacher** [comment]
trello link just in case anybody ever cares and wants to easily find here:

https://trello.com/b/WXcDIQYd/dc-a4c-2-0-viz
