### ISSUE TITLE
Integrate neighborhood layer switching into main JS file

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#13]
Right now there are two JS files with code we've worked on. One for the point interactions Aaron was working on and another with work me and Emily did on Oct. 27. Shouldn't be too hard to bring these together, but in case I stepped on any toes I kept them separate. Just need someone to bring them together once things are working right.

**Comment by ajschumacher** [comment]
I've merged everything so there's just visualization.js and index.html again. Life is good. We work from here.
