### ISSUE TITLE
Abstract schools layer to display other points layers

### ISSUE THREAD

**Issue by cmgiven** [DCActionforChildren/dcaction#138]
Needed for #136 and for showing library locations.

**Comment by ajschumacher** [comment]
go @cmgiven go!

**Comment by shanab202** [comment]
great catch-- thanks @cmgiven!!!

**Comment by cmgiven** [comment]
Here's my initial sense of how this should be integrated into the menu. Let's hear if anyone was thinking something else.

![screen shot 2015-04-09 at 6 16 19 pm](https://cloud.githubusercontent.com/assets/5375557/7078377/822534a0-dee6-11e4-8d34-09c2d9704c1e.png)

**Comment by cmgiven** [comment]
Hospital points are functional on the `points` branch on my fork. The info panel still needs to be updated.

https://github.com/cmgiven/dcaction/tree/points

**Comment by cmgiven** [comment]
Screenshot with _all_ the points. Need a new color palette for the points.

![screen shot 2015-04-09 at 7 27 28 pm](https://cloud.githubusercontent.com/assets/5375557/7079114/9dd3c164-deee-11e4-968f-730c6f03aebf.png)

**Comment by shanab202** [comment]
This looks awesome @cmgiven!!! The green points = hospitals, correct?

**Comment by cmgiven** [comment]
Correct. Note that we should change the colors to a better palette before this goes live.

—

**Comment by hyesookchung** [comment]
AWESOME. thanks Chris!

**Comment by joshdelarosa1** [comment]
@shanab202 @hyesookchung @timothywvance If @cmgiven solution meets the requirements, can we close this issue and #97 and go live with these points?

Also, did we pick a color scheme yet?  If not, could someone pick a color using http://colorbrewer2.org/ ?  Janet and I recommend diverging, 7, color blind safe:

![screen shot 2015-04-22 at 7 31 01 pm](https://cloud.githubusercontent.com/assets/5900421/7287741/2e3f2d7e-e926-11e4-9931-027720049af4.png)

**Comment by shanab202** [comment]
Thanks @joshdelarosa1. @cmgiven-- in your comment above the palette, were you referring to the color of the points (using both red and green) or the chloropleth for the map legend mentioned in #97? We are fine with the blue for the map, but do not want the points to be confusing, especially for color blind folks.

**Comment by cmgiven** [comment]
Color of the points. Yes, we need an accessible categorical scheme.

Also note that there's additional work on this issue remaining, mostly around extracting the popover panel.

**Comment by cmgiven** [comment]
Complete with 866b7b6. Note that we use two colors, one for schools and one for other POIs, and change the shape of the school depending on DCPS/Charter.
