### ISSUE TITLE
Add Leaflet background to D3 visualization

### ISSUE THREAD

**Issue by ajschumacher** [DCActionforChildren/dcaction#14]
Right now we have our polygons floating on white with not roads or landmarks to provide guidance for users of what they are clicking on. Adding a tile layer backdrop for our translucent polygons to float over will provide more context for each neighborhood.

Peter suggests doing something like this:

http://bost.ocks.org/mike/leaflet/

This would give nice mapping in the background, which could be nice.

We could use Open Street Map as a backdrop.

**Comment by akilism** [comment]
I'll try to get this working for you guys. I actually  have just done something like this for a project I'm working on at  https://intense-savannah-5613.herokuapp.com/city/

**Comment by jonroberts** [comment]
Done in the addBackgroundMap branch.
