### ISSUE TITLE
Revising Data and Documentation of Single Mother Households

### ISSUE THREAD

**Issue by joshdelarosa1** [DCActionforChildren/dcaction#156]
on fetch_acs.rb program -

Rename: from ’single_mother_families_numer’ => 'B09002_015E’, to ’single_mother_families_numer’ => 'B09002_015E',

Add ’total_families_denom’ => 'B09002_001E’,

single_mother_families_perc = single_mother_families_numer/ total_families_denom

**Comment by jotok** [comment]
Is there an error in the "Rename" request? I don't see a difference between the two entries.

To compute `single_mother_families_perc` as a ratio, I need to compute the numerator and denominator as `single_mother_families_perc_numer` and `single_mother_families_percent_denom`. I assume that there will not be a problem removing `single_mother_families_numer` from the configuration file. Do you agree?

**Comment by cmgiven** [comment]
Have renamed the following labels:

Children in Single Mother Families -> Single mother families

Percentage of Children in Single Mother Families -> Percentage of Single Mother Families

Fixed as part of the #142 branch.

**Comment by cmgiven** [comment]
Change now live.

**Comment by joshdelarosa1** [comment]
We need to update the methodology to read:

Estimated percent of families with children headed by a single mother of the total number of families with children in a neighborhood.
