### ISSUE TITLE
Remove "new" tag on indicators

### ISSUE THREAD

**Issue by shanab202** [DCActionforChildren/dcaction#169]
There are few datasets that have a red "new" label next to them-- hospitals, libraries, and average median income. How can we remove these?

**Comment by ajschumacher** [comment]
Ooh I think I saw "new" as a column in `data/fields.csv` - @cmgiven?

**Comment by gggodhwani** [comment]
Yes, if we remove TRUE value from 'new' column and commit data/fields.csv, then that red 'new' label would get removed.

**Comment by ajschumacher** [comment]
I will do it! I'm reckless!

**Comment by ajschumacher** [comment]
Did that fix it?

**Comment by shanab202** [comment]
Yes-- thanks for the quick fix!!!

**Comment by ajschumacher** [comment]
![](https://media.giphy.com/media/sHytgXD2vlNVC/giphy.gif)

**Comment by cmgiven** [comment]
👍 to all of this.
