### ISSUE TITLE
Create legends

### ISSUE THREAD

**Issue by bonnieok** [DCActionforChildren/dcaction#23]
We need to forward the breakpoints expressed in the visualization.js file to this legend box. Ideally, where breakpoints are percentages, we need to have the legend box expressing them as such. Below is an example of how the code lists these breakpoints:

  'math' : {
    'domain' : [0.14, 0.355, 0.54, 0.75],
    'range' : ["#e5ffc7", "#d9fcb9", "#bbef8e", "#9ad363", "#6eb43f"]
  },

The legend in this instance would read like:

0-14%
14%-35.5%
35.5%-54%
54%-75%
75% and up

**Comment by nickmcclellan** [comment]
It's probably possible for us to set up individual legend labels for each layer. This might be ideal for differently formatted data points. Plus it would be more accurate!

Here's an example of legend labels expressed on a D3 map:

http://bl.ocks.org/KoGor/5685876

**Comment by nickmcclellan** [comment]
After some great work from @Solomon, this is done!

**Comment by pdarche** [comment]
Huzzah!

On Mon, May 12, 2014 at 2:35 PM, nickmcclellan notifications@github.comwrote:

> Closed #23 https://github.com/nickmcclellan/dcaction/issues/23.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nickmcclellan/dcaction/issues/23#event-120250265
> .

## 

Peter Darche
(415) 595-2940
