### ISSUE TITLE
Update DC Action logo/branding

### ISSUE THREAD

**Issue by bonnieok** [DCActionforChildren/dcaction#24]
![dc_kids_count_logo_lightblue_noperiods](https://f.cloud.github.com/assets/6025723/1924765/52fe2662-7e27-11e3-9a23-37682ded6db4.jpg)

See correct DC Kids Count logo with no periods, above.

**Comment by nickmcclellan** [comment]
Hey Bonnie, do you have this in a higher resolution or in a vector format? That would help a lot! I've added this to the demo, but I can optimize the logo if I have a vector version.
