### ISSUE TITLE
Check Child Poverty

### ISSUE THREAD

**Issue by bonnieok** [DCActionforChildren/dcaction#25]
Child poverty numbers being pulled from the census look way off - need to retrace steps.

**Comment by joshdelarosa1** [comment]
This formulas was corrected:

"(B17001_004E+B17001_005E+B17001_006E+B17001_007E+B17001_008E+B17001_009E+B17001_018E+B17001_019E+B17001_020E+B17001_021E+B17001_022E+B17001_023E) /

(B17001_033E+B17001_034E+B17001_035E+B17001_036E+B17001_037E+B17001_038E+B17001_047E+B17001_048E+B17001_049E+B17001_050E+B17001_051E+B17001_052E + B17001_004E+B17001_005E+B17001_006E+B17001_007E+B17001_008E+B17001_009E+B17001_018E+B17001_019E+B17001_020E+B17001_021E+B17001_022E+B17001_023E)"

**Comment by nickmcclellan** [comment]
We fixed this in our last data dive. Thanks everyone!
