### ISSUE TITLE
Include source information for each layer

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#27]
We need to add descriptions of our sourcing for each layer when a user clicks each layer. Each layer's sourcing is described in our variable validation spreadsheet:

https://www.dropbox.com/s/z32f54jsbuqlfxq/Indicator%20Tracking%20Updated%202014-01-08.xlsx

Where possible we’d like to link back to these sources (to the Census, for example).

**Comment by charlesdguthrie** [comment]
I built source functionality for dummy data in my own branch.  All I need is the real dataset and I'll connect it and send a pull request.

**Comment by nickmcclellan** [comment]
Closing this thanks to some amazing work from @charlesdguthrie!

**Comment by charlesdguthrie** [comment]
Wonderful!  Glad to check that off the list
