### ISSUE TITLE
Clear menu when neighborhood is rolled upon or selected

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#28]
Right now, when a layer is selected and the user begins to explore the neighborhood information, it's not possible to see the sidebar information that displays data values.

On rollover or click, it would be nice if the menu of layers would slide back left to leave an unobstructed view of the whole graphic.

**Comment by akilism** [comment]
Hey, I got this done also I didn't submit a pull request though as it's relying on some of the changes from the other pull request for the mouseover issue.

**Comment by akilism** [comment]
Fixed.
