### ISSUE TITLE
Fix number display for data points in sidebar

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#29]
Right now, selecting neighborhoods will display data from our CSV but it is not adding commas to figures in the thousands or correcting percentages to display as percentages and not decimals. For these relevant data points, we'd like to transform the display of these numerals.

**Comment by akilism** [comment]
I took a look at this but i'm not sure I fully understand the data. I can add the commas in easy enough and get a quick and dirty solution for the percentages...but there are vaules that I don't get, like fractional population counts. Sometimes total population is like 1230.023?

**Comment by nickmcclellan** [comment]
Thanks for the help Akil! So the reason a population count would have trailing decimal points like that is because that number was computed by spatially joining smaller geometries into the neighborhood cluster. It is an estimation of what the population count for that neighborhood would be if the smaller geometries were combined. In some cases, the neighborhood cuts through one of these smaller geometries, resulting in decimal estimations. For counts, it's fine to just round this to the nearest whole number.

Our favored longterm procedure for updating data, however, will have our script hitting the Census API for updated numbers and crosswalking them to the neighborhood level, resulting in decimal points on occasion. It would be ideal for the visualization to parse these out instead of editing the CSV, but if we want to make the number translation in the CSV, I can talk to our data folks about having our Census script make the adjustment for us. I figured transforming in the visualization.js would be ideal, hence the issue.

Thanks for taking a look at this!

**Comment by akilism** [comment]
Fixed in commit: https://github.com/nickmcclellan/dcaction/commit/d0afc64efb962bf1ccb089c0b58f7df9bb504102
