### ISSUE TITLE
Display neighborhood name and data on hover

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#30]
Right now data and neighborhood names will only appear on click. We need the neighborhood names and data to appear on hover as well. The difference between hover and click should be that, when clicked, the hover interaction will cease and the graphic will zoom to the selected neighborhood. Clicking again will zoom out and resume the hover interaction.

**Comment by akilism** [comment]
Hi! I submitted a pull request for this issue.

**Comment by akilism** [comment]
Pull request #31 took care of this.
