### ISSUE TITLE
Fix duplicate school display.

### ISSUE THREAD

**Issue by akilism** [DCActionforChildren/dcaction#32]
Clicking on a school always adds a new info box to the page. 

Not sure if the best behavior is to only ever have one displayed, or only ever have one for a single school displayed? Maybe limit it to X amount at a time?

**Comment by nickmcclellan** [comment]
Hey Akil! Sorry I haven't replied to this. I think you're right, we had intended to leave it to 2-3 schools and always allow the three most recently clicked schools to remain visible. Is that something you could tackle?

**Comment by akilism** [comment]
Hey Nick I'll take a look at this tonight.

**Comment by nickmcclellan** [comment]
Hey Akil! Thanks so much for your help on this again. I jumped into the code today, cleaned some of it up, and altered your code just a bit. I created a separate school div for the point information an restructured how it displays.

When you take a look at limiting the number of schools visible on click, can you do one more thing?

Is it possible to hide the schools box until a point is clicked? Right now I have to display it on the page for the .prepend code to work and it would be great if it remained invisible until a point is clicked.

I bet I could stumble through it but I don't want to mess with your work any more than I have to. Thanks again so much!

**Comment by akilism** [comment]
yep sure thing

**Comment by akilism** [comment]
Fixed this in commit 944df282dbada453d39eb8393f7ad5a5204da302.
