### ISSUE TITLE
Add selected metric to sidebar that dynamically changes depending on which layer is selected

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#33]
The primary metric in the sidebar should be the visualized measure on the current layer selected. As the user switches layers, this measure sure change to reflect the chosen variable. 
As demonstrated here:
![select](https://f.cloud.github.com/assets/1339437/2062445/eaec633a-8c8c-11e3-8132-beeddbb4fd14.png)

**Comment by akilism** [comment]
fixed in commit dd65f41d1d6043faee8b22f553c452d81ab18f0e
