### ISSUE TITLE
Add charter school data as a point layer

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#40]
We would like to add a layer (similar to the public school layer, it would need to behave as is described in issue #39)

I will provide a CSV file for this in the data folder, it will be named charter.csv and will be structured the same way as the public school point layer.

**Comment by akilism** [comment]
Hey Nick! 

I didn't see this issue, I made a change to load the dc public charters information from data/charters.json and the dc public schools from data/schools.json. It just looks like there are some extra fields in the json files? 

This change is in commit 10ef8fe15697be75295c17030cbcbccbfbcf68fb.
