### ISSUE TITLE
Allow charter school and public school data to appear together on the same map (using the packMetros method)

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#42]
We'd like the logic of the point layers to work a bit differently than the choropleth layers. Whereas choropleth layers cannot be placed on the map together (only one at a time), we'd like the public and charter school points to appear on the map together, if the user chooses.

Right now we have a function applied to the public schools that allows each circle to clear it's immediate area and "push" schools out of the way so it is easy to distinguish between points in an area where schools are clustered.

Obviously, adding charter schools to the map will greatly clutter it, so we'd like the same function applied when this layer is added. Ideally, both of these layers will push eachother out of the way so you don't have any public school or charter school points on top of one another.

We adapted the packMetros method from one of the D3 examples listed on Mike Bostock's site: http://trends.truliablog.com/vis/metro-movers/

**Comment by nickmcclellan** [comment]
Hey @akilism, wondering if maybe you can take a look at this one issue for us. We can probably launch without this functionality, but I think maybe you might make short work of it before our May 1 deadline for resolving issues. Let me know if you can help! Thanks for everything.

**Comment by akilism** [comment]
@nickmcclellan Yep I'll take a look at it tonight.

**Comment by akilism** [comment]
Hey @nickmcclellan I just pushed up a change to take care of this.

**Comment by nickmcclellan** [comment]
This is working! Thanks @akilism!
