### ISSUE TITLE
Verify formula for "children in poverty" variable

### ISSUE THREAD

**Issue by jotok** [DCActionforChildren/dcaction#44]
In the dcaction_datacolumns spreadsheet, the "children in poverty" variable includes the variable "B17001_00+E" which I believe should be "B17001_008E".

**Comment by joshdelarosa1** [comment]
That was a mistake.  The formula should be: kids in poverty / (kids in poverty + kids not in poverty)

**Comment by jotok** [comment]
I'm leaving my substitution: "B17001_00+E" => "B17001_008E".
