### ISSUE TITLE
Verify formula for "No HS Degree (25+)" in the dcaction_datacolumns spreadsheet

### ISSUE THREAD

**Issue by jotok** [DCActionforChildren/dcaction#45]
The formula currently given is a ratio minus a value: (x + y + z)/w - (a + b)
I just want to confirm that this is correct.

**Comment by joshdelarosa1** [comment]
Cleaned up the parentheses

B15001_012E+B15001_013E+B15001_020E+B15001_021e+B15001_028e+B15001_029e+B15001_036E+B15001_037E+B15001_053E+B15001_054E+B15001_061E+B15001_062E+B15001_069E+B15001_070E+B15001_077E+B15001_078E/
(B15001_001E-(B15001_003E+B15001_044E))

Male and female over 25+ without HS / Total population - (male 18-24 pop + female 18-24 pop)

**Comment by charlesdguthrie** [comment]
This looks like it's still a ratio minus a value.

**Comment by joshdelarosa1** [comment]
To verify the formula I calculated the DC 25+ no HS degree rate.  The city wide rate is 12.47%.

You can see my work here:  https://drive.google.com/file/d/0B6e0RxBr5-9jTVNJdkNIQ0FpRUk/edit?usp=sharing

Either there is a bug in the API or the formula is not being translated or cross-walked correctly in the script.

Could you compare the script to the formula:  

B15001_012E+B15001_013E+B15001_020E+B15001_021e+B15001_028e+B15001_029e+B15001_036E+B15001_037E+B15001_053E+B15001_054E+B15001_061E+B15001_062E+B15001_069E+B15001_070E+B15001_077E+B15001_078E/
(B15001_001E-(B15001_003E+B15001_044E))

or my spreadsheet ( https://drive.google.com/file/d/0B6e0RxBr5-9jTVNJdkNIQ0FpRUk/edit?usp=sharing)

If the value is still negative, please let me know.

**Comment by joshdelarosa1** [comment]
When checking the script, please start with the denominator.  It should say (B15001_001E-(B15001_003E+B15001_044E))

Which is:25+ population=  (total population - (male 18-24 population+female 18-24 population)).  

All of the numerator values are positive.  So if there is a negative in the numerator, there could be a bug in the Census API system.

**Comment by jotok** [comment]
I've updated the script to use Josh D's formula from this comment thread.
