### ISSUE TITLE
Verify formula fo "No HS Degree (18-24)" in the dcation_datacolumns spreadsheet

### ISSUE THREAD

**Issue by jotok** [DCActionforChildren/dcaction#46]
The formula is a number added to a ratio: a + (b + c)/(x + y).
I want to confirm this is correct.

**Comment by joshdelarosa1** [comment]
I cleaned up the parentheses.
(B15001_004E+B15001_005E+B15001_045E+B15001_046E )/
 (B15001_003E+B15001_044E)

What we are saying is: 18 no HS degree = (male 18-14 less than 9th grade + male 18-24 no HS + female 18-14 less than 9th grade + female 18-24 no HS )/ (total 18-25 male + total 18-25 female)

**Comment by jotok** [comment]
I've updated the script to use this formula.
