### ISSUE TITLE
Clear schools

### ISSUE THREAD

**Issue by bonnieok** [DCActionforChildren/dcaction#53]
Give some option to clear selected school data entirely.

**Comment by akilism** [comment]
@bonnieok Is this referring to the school locations on the map or the box of school information that pops up on the right?

**Comment by nickmcclellan** [comment]
That refers to the box on the map, in case users want to clear it when they scroll around. I was planning on adding a close button that users could click to remove the DIV from the map. Do you have any thoughts on how better to do it?

**Comment by akilism** [comment]
I think that's good, this already semi-exists if you click on the name of
the school it will remove itself. shouldn't be too hard to get it to remove
them all with a single close button.. If you need I can probably bang this
out quickly tomorrow sometime.

**Comment by akilism** [comment]
Pushed up a change for this.

**Comment by ShubhaBala** [comment]
This looks good - however clicking the close button doesn't remove the box itself.

**Comment by ShubhaBala** [comment]
It seems to work sometimes but not others.  It seems that when there are charter schools only, the box clears.  Sometimes with public schools it doesn't close.

**Comment by akilism** [comment]
@ShubhaBala Thanks for pointing this out. I think I see the problem...when you clear all the schools by clicking the name of the school then on subsequent popups the close button doesn't seem to be functioning correctly (not closing the entire window). I'll take a look at this tonight it should be a simple fix.

**Comment by nickmcclellan** [comment]
This appears to be working now, I'm closing the issue.
