### ISSUE TITLE
Remove median family income

### ISSUE THREAD

**Issue by bonnieok** [DCActionforChildren/dcaction#56]
Didn't we decide not to display median family income because it is an average of medians?

**Comment by shanab202** [comment]
Hey math wizards! We have received a lot of questions about this indicator (like why it's not included). Is there a way to avoid doing an average of medians in order to make this available on the tool? If so, how long would it take to work on this? Thanks!

**Comment by nickmcclellan** [comment]
We removed it because displaying an average of median income is not median income. It was pointed to be statistically unsound by Josh so we kept it out.

**Comment by shanab202** [comment]
Thanks, Nick! Do we have a way to get a statistically sound values for each neighborhood?

**Comment by jotok** [comment]
I don't think there's any way to compute true median values at the
neighborhood level from the tract data. We can certainly compute a weighted
average of median values, but we decided that this is an unusual statistic
and that it would be too confusing. Maybe we should revisit the last point.
How weird/ethical would it be for us to report a "median" value with a big
asterisk explaining that it was actually an average of medians?

**Comment by shanab202** [comment]
Hi Josh. Thanks for weighing in ! We actually do it in the KIDS COUNT Data Center and explain how we got the calculation in the footnotes:

http://datacenter.kidscount.org/data/tables/7396-median-income-of-families-with-children-by-neighborhood?loc=10&loct=3#detailed/3/any/false/971/3608,3490,3566,3567,3568,3569,3570,3571,3572,3573,3574,3575,3576,3577,3578,3579,3580,3581,3582,3583,3584,3585,3586,3587,3588,3589,3590,3591,3592,3593,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603,3604/14478

My question, which may not be easily answered, is how far from the "truth" is this calculation?
