### ISSUE TITLE
Clarify names of child success indicators

### ISSUE THREAD

**Issue by bonnieok** [DCActionforChildren/dcaction#58]
Clarify, either in the source box or in the indicator title that math and reading scores are by neighborhood of residence, while graduation rate is by school location. Neighborhoods with no high school therefore, no graduation rate, should display as blank/grey.

**Comment by nickmcclellan** [comment]
Didn't we decide to not include graduation rate by neighborhood and by school points instead?

**Comment by bonnieok** [comment]
I think that makes more sense- feel free to delete that layer.

On Monday, April 14, 2014, nickmcclellan notifications@github.com wrote:

> Didn't we decide to not include graduation rate by neighborhood and by
> school points instead?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nickmcclellan/dcaction/issues/58#issuecomment-40381878
> .

## 

Bonnie O'Keefe
202.258.7264
