### ISSUE TITLE
Fix drag navigation on map

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#64]
The issue here is that dragging or scrolling through the map sometimes increases load times and brings us some place we don't want to be (like West Virginia).

Is it possible to set up panning extents on the map? Also, can we set maximum zoom levels? Anything that can reasonably minimize the lag time of loading new map tiles when a user scroll or pans too far. Thanks!

**Comment by hyesookchung** [comment]
Pete -- I am just remembering you were going to reach out to someone -- simply wanted to flag this for you just in case. thanks

**Comment by pdarche** [comment]
Thanks, HyeSook!  Nick, I'm under the impressions this was close.  Is this
mistaken?

On Wed, May 28, 2014 at 7:03 PM, HyeSook Chung notifications@github.com
wrote:

> Pete -- I am just remembering you were going to reach out to someone --
> simply wanted to flag this for you just in case. thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DCActionforChildren/dcaction/issues/64#issuecomment-44475900
> .

## 

Peter Darche
(415) 595-2940

**Comment by nickmcclellan** [comment]
Nope, I don't think panning extents have been added to the graphic. I emailed @jonroberts about it but I think he hasn't gotten to it. We launched anyway though, but I think having a limit on where users could pan would still be useful.

**Comment by jonroberts** [comment]
I'll take a shot at it this evening.

**Comment by hyesookchung** [comment]
Thanks Jon! We have to somehow figure out how to pull all our friends from NYC to hang out with us!
