### ISSUE TITLE
Error in race demographic breakdown of 'Under 18' on the map

### ISSUE THREAD

**Issue by JyothisS** [DCActionforChildren/dcaction#65]
The race demographic percentage breakdown of 'Under 18' is incorrect on the map - http://nickmcclellan.github.io/dcaction/.

Based on a check of Cluster 4 and Cluster 16:
The white_under_18, black_under_18, hispanic_under_18, other_under_18 variable values is correct in the spreadsheet - https://docs.google.com/spreadsheet/ccc?key=0AliQRBwTvad9dC1reWl1NUpXVkEyUXBQOVNGNUV6dFE&usp=sharing#gid=17. But, the race percentage breakdown of 'Under 18' on the map does not match the percentage breakdown in the spreadsheet.

**Comment by JyothisS** [comment]
Similarly, the 'Over 18' race demographic percentage breakdown on the map does not match the breakdown calculated from the spreadsheet.

**Comment by nickmcclellan** [comment]
See reason for closing issue #66
