### ISSUE TITLE
Error in 'other_18' variable value

### ISSUE THREAD

**Issue by JyothisS** [DCActionforChildren/dcaction#66]
The value of 'other_18' variable equals 'other_under_18' variable in the spreadsheet https://docs.google.com/spreadsheet/ccc?key=0AliQRBwTvad9dC1reWl1NUpXVkEyUXBQOVNGNUV6dFE&usp=sharing#gid=17.

The error is with 'other_18'. The 'other_under_18' variable in the spreadsheet is accurate.

**Comment by nickmcclellan** [comment]
The reason for this is we used Census 2010 data in our previous graphic and it is still the most accurate source of demographic information at these small geographies. Using the recent ACS data could be inaccurate.

**Comment by JyothisS** [comment]
Thanks for responding. I am inserting your comment into the DCAC Indicator Tracking sheet for future reference and updating the '2014 Data Book Source' column as it mentioned 2008-2012 ACS data as the source. https://docs.google.com/spreadsheet/ccc?key=0AiwzbU_iFRRWdEdxbmtDaGE4b3R3LXBSUUN3VXJQMEE&usp=sharing#gid=1.

**Comment by JyothisS** [comment]
But, shouldn't the value of 'other_18' variable in the 'FullDataBookV2' workbook of the spreadsheet not be equal to the 'other_under_18' variable? In case we do end up using the ACS 2008-2012 values at some point this would need to be rectified.

**Comment by JyothisS** [comment]
If the 2010 census data is being used for the race demographic breakdown - Is the data being pulled from the workbook 'DataBookV1'? If it is then the 'Hispanic Over 18' data is pulling the 'Hispanic Under 18' data. For example in Cluster 16: Colonial Village the 'Over 18' data adds up to 104%.

**Comment by nickmcclellan** [comment]
Hey Jyothis,

I added a few columns to the aggregated spreadsheet with the variables I'm using in the graphic. I don't think the other_18 and other_under_18 variables match...actually there are completely different names for the census variables: pop_nothisp_white, pop_nothisp_black, pop_nothisp_other, pop_hisp, pop_nothisp_white_under18, pop_nothisp_black_under18, pop_nothisp_other_under18, pop_hisp_under18. Are you seeing the same issues with these columns?

**Comment by JyothisS** [comment]
Hey Nick,

Thanks for all the work and helping with better clarity on the data. I think what is happening is that in the map the (Hispanic Over 18) is showing the same values as (Hispanic Under 18).

Thanks,
Jyothis

**Comment by nickmcclellan** [comment]
Great catch Jyothis! Just fixed it.

**Comment by JyothisS** [comment]
Thanks for fixing it.
