### ISSUE TITLE
Issue with 'Ratio of child care capacity to child population' and 'Ratio of child care capacity to child in poverty' data

### ISSUE THREAD

**Issue by JyothisS** [DCActionforChildren/dcaction#68]
'Ratio of child care capacity to child population' shows a higher ratio than 'Ratio of child care capacity to child in poverty'. Under5 population would be greater than or equal to under5 poverty population. Therefore ratio of child care capacity/child population should be lower than the ratio of child care capacity/child in poverty.

**Comment by JyothisS** [comment]
Where is the final data residing for Under5 population and Under5 poverty for the above calculations and the variable slugs cc_ratio and cc_ratio_demand?

**Comment by nickmcclellan** [comment]
I have recalculated these variables, I believe they should be correct now. I'm worried there might be a bug with displaying the ratios that are > 1, they may not show up as percentages in the graphic. We may need to set up an issue for this specific layer.
