### ISSUE TITLE
Change in the indicator - Single mother families

### ISSUE THREAD

**Issue by JyothisS** [DCActionforChildren/dcaction#69]
The indicator 'Single mother families' is pulling the ACS data 'number of children in single mother families. Hence the indicator name needs to change to 'Percentage of children in single mother families'. And the value needs to be presented as a percentage.

**Comment by nickmcclellan** [comment]
I was able to calculate this correctly, great catch Jyothis!

**Comment by JyothisS** [comment]
Thanks for correcting it. Please do change the name of the indicator to 'Percentage of children in single mother families'.

**Comment by JyothisS** [comment]
Hi Nick,
The table on the Right Side says 'Single mother families'. I don't know whether there is space for 'Percentage of children in single mother families'. It could be changed to 'Children in single mother families'.

Thanks.
