### ISSUE TITLE
Integrate school and neighborhood info cards with visualization layers

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#7]
Right now, we only have basic information for school points popping up in the sidebar. It's possible to display multiple information from schools, but this information has not been styled and all requested data does not display.

We'd like for the sidebar to populate with data from the neighborhood shapes and school/child care center points. The data reflected should appear similar to the school and neighborhood storyboards.
![map-interface](https://f.cloud.github.com/assets/1339437/1378262/52b7a8aa-3ac4-11e3-91bc-1af454d6d5e7.png)
![budget-interface](https://f.cloud.github.com/assets/1339437/1378263/5ce5af02-3ac4-11e3-95a9-502bfc705866.png)

**Comment by ajschumacher** [comment]
From Nick's other issue:

"""
While the 1.0 e-Databook populated the sidebar with information for neighborhoods as the user rolled over, we'd like the sidebar information for point based data to allow multiple schools/child care centers to be compared.

When the user rolls over the points, it will populate the sidebar with information about that school or child care center. However, if they click, they will collect info cards from multiple points, however many they click, so they may compare multiple schools.

This interaction is partly working on the D3 skeleton now, although not all data points are being called into the infocards and the design is not especially elegant.
"""

**Comment by ajschumacher** [comment]
There is now a function "displaySchoolData" in visualization.js which is where this could be done. Right now it's just writing raw html; it could be done in some more clever way if somebody wants to get all mvc on it, but I don't know if we need that much engineering on this one.
