### ISSUE TITLE
Violent crime rate

### ISSUE THREAD

**Issue by JyothisS** [DCActionforChildren/dcaction#71]
Issues with the violent crime rate:
Currently the data presented is just the total violent crimes for each cluster. The numbers are wrong, they sum up to only 99 violent crimes for all the clusters. There was definitely more than 99 violent crimes in DC - http://mpdc.dc.gov/node/199172. I think the original file indicated in DCAC Indicator Tracking file has data only for some of the violent crimes and for only a single day - 12/16/2011.

Once the total violent crimes is identified it would also need to be converted to the violent crime rate - all reported violent crime incidents/1,000 population. 

Thanks.

**Comment by nickmcclellan** [comment]
Jyothis, this is the primary source for the data layer: https://docs.google.com/spreadsheet/ccc?key=0AliQRBwTvad9dC1reWl1NUpXVkEyUXBQOVNGNUV6dFE&usp=drive_web#gid=0

There are only 100 incidents there. Do you have an updated sheet? I'm glad to add that to the aggregation spreadsheet and output the updated layer so we can close this issue.

**Comment by nickmcclellan** [comment]
I went ahead and found this in the Dropbox and added it to our aggregation spreadsheet. As a result, I was able to include five extra layers of data for this variable. All of it is visible on the visualization.

**Comment by JyothisS** [comment]
Hi Nick,
Sorry for not getting back, we had an internet/mail server blackout for the last five days. The data from the dropbox for the five extra layers and the total violent crime is still incorrect. But having those extra layers is a bonus. Thanks. I will send the updated data from MPD for year 2012 within the next hour. (Reopening the issue)

**Comment by JyothisS** [comment]
Hi Nick,
I have mailed you the required data for violent crimes for 2012. Can we have both displayed -  the total number for each crime category and the crime rate (per 1000 population)?
Thanks,

**Comment by nickmcclellan** [comment]
I've added the per capita measures and updated the data. I should point out I think the counts make a better data layer for at least the individual crimes. I think per capita is best fleshed out with all crimes combined, let me know what you prefer.

**Comment by JyothisS** [comment]
Yes, that is what I was asking - is it possible to have both, the counts as well as the crime rates displayed for total violent crimes and for each crime category?

The crime rates is per 1'000 population, so the crime rate for each cluster = (crime counts for cluster / population of cluster)*1000.

There is still some issue with the numbers when shown as per capita. They are too high.

Thanks,
