### ISSUE TITLE
recent merge

### ISSUE THREAD

**Issue by akilism** [DCActionforChildren/dcaction#72]
@nickmcclellan I think there is a recent merge that took out some of the work I did last week.

Issues #55, #53 and #42 were all fixed and now look to be broken again.

**Comment by nickmcclellan** [comment]
Sorry about this! I will try to reverse. I should have synced first X-(

**Comment by akilism** [comment]
@nickmcclellan If you can't figure it out and need me to redo the changes just let me know.

**Comment by nickmcclellan** [comment]
I think I figured it out. Please double check for me. I can see the schools popping up on the same map, the zoom appears less buggy, and I can clear schools. I'll try to tread lightly!

**Comment by akilism** [comment]
Hey just took a look everything seems good. Thanks for letting me help you
guys out with this!
