### ISSUE TITLE
Freeze neighborhood info box on neighborhood click

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#73]
This is something that keeps randomly breaking. A recent commit has left it unhinged again. Basically, on click, we'd like the rollover behavior to cease for neighborhoods. That way users can freeze on their neighborhood while they cycle through different layers or schools.

It's been a quick fix before and I am not sure where to fix it myself. Can anyone take a look? I know @eschow fixed it last time.

**Comment by akilism** [comment]
@nickmcclellan This should be fixed, please take a look and let me know.

Also fixed a little bug with the schools panel not always hiding itself.

**Comment by nickmcclellan** [comment]
Thanks @akilism! Just one question: On line 750, there's a function that no longer works: bringNeighborhoodToFront();

Is there any reason this fix would break that function? Kind of a minor thing, but just a curious item to get unstuck in the wake of some of tonight's commits.

**Comment by akilism** [comment]
@nickmcclellan Yeah my bad it wasn't getting called anymore. I just pushed up a fix.

**Comment by nickmcclellan** [comment]
Hey @akilism I don't know if this other recent bug is related, but the map colors are clearing after we zoom the map now. Do you think this is in any way related? I'm not sure why all these new bugs keep appearing after we squash old bugs.

**Comment by akilism** [comment]
@nickmcclellan I'm not sure it might have to do with the new col names and how the redraw is handled when zooming. I'm at work right now but I'll take another look tonight and see if I can iron it out.

**Comment by nickmcclellan** [comment]
I'm going to go through previous commits of visualization.js to see if I can narrow down when the problem occurred. Thanks @akilism!

**Comment by akilism** [comment]
@nickmcclellan  I'm pretty sure it's going to be somewhere around lines 239-243

```
.style("fill",function(d) {
    if (currentMetric === null) { return "#aaaaaa"; }
    var totalPop = all_data[d.properties.gis_id].population_total;
    return totalPop > min_population ? choro_color(all_data[d.properties.gis_id][currentMetric]) : defaultColor;
})
```

**Comment by nickmcclellan** [comment]
Thanks @akilism! You were right on. I was able to fix this myself. So excited when I can say I did that :+1:

**Comment by akilism** [comment]
Great! Let me know if there's any other issues you need help with.
