### ISSUE TITLE
Correct all source info and links

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#76]
I need some help making sure all of our layers are sourced correctly. There is a spreadsheet in the GitHub that should make it pretty clear, just help me fill in the source text and URLs. You may link to the National Kids Count website where possible: https://github.com/nickmcclellan/dcaction/blob/gh-pages/data/source_dummy.csv

**Comment by JyothisS** [comment]
Hope you received the required file with the source text and URLs.
