### ISSUE TITLE
Crime Rates

### ISSUE THREAD

**Issue by JyothisS** [DCActionforChildren/dcaction#77]
I think everywhere the value is less than 1, it is showing up as a percentage instead of the actual value.

The Homicides per 1,000 residents is showing up as a percentage. Most of the numbers are in decimal points. For example: Columbia Heights should be 0.084 not 8%. Also for other other crime categories per 1,000 residents wherever the value is less than 1 it is displaying a percentage.

**Comment by nickmcclellan** [comment]
Closing #78 should resolve this issue.
