### ISSUE TITLE
Rework code to read number formatting from data column suffix

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#78]
So we have a long-standing bug in the graphic concerning how data is interpreted from our spreadsheet and displayed alongside the map. Right now, it's assuming any number from the spreadsheet that is between 0 and 1 is a percentage and every other number is a value. This works most of the time, but we do have a few instances where percentages and values do not conform to these conditions. Also, we have at least one column that should be formatted as U.S. currency.

The problem occurs on line 780 of visualization.js, the getDisplayValue function. I'm hoping we could adjust this to respond to the suffice of a data column header to format the number accordingly. 

I've gone through the neighborhoods2.csv file and renamed every data column to include the following suffixes: _val (a regular value with only commas for thousand markers where appropriate, _perc (a percentage that must be multiplied by 100 and appended with a percentage sign), and _cur (a value that needs a comma for thousand markers as well as a dollar sign).

I'm hoping that adding these suffixes will make rewriting the getDisplayValue function extra easy. If there's a better approach, I'm open to reworking the data in any way to get to it.

The only other way was to set up conditionals for groups of variables, and I just thought that would get unruly in the code. Plus, this way, we can make these formatting adjustments from the spreadsheet.

Thanks, please comment if you have any questions!

**Comment by akilism** [comment]
@nickmcclellan i'll take care of this tonight.

**Comment by akilism** [comment]
@nickmcclellan Hey Nick, I've made this change please take a look and let me know if you need any additional changes. 

One of the col's that is reported as a percentage looks like its already calculated though. 
cc_child_pov_perc

**Comment by nickmcclellan** [comment]
Thanks a ton @akilism! I hope reworking the data made this an easy lift. This is a major improvement for the data and squashes a persistent bug. I will follow up with @Jyothis-DCAction about that variable, I'm pretty sure I'm calculating it incorrectly. Waiting on @pdarche to run a Ruby script for me so I can update it.

**Comment by pdarche** [comment]
D'oh!  Sorry!  Just reran!

On Mon, May 12, 2014 at 10:26 PM, nickmcclellan notifications@github.comwrote:

> Thanks a ton @akilism https://github.com/akilism! I hope reworking the
> data made this an easy lift. This is a major improvement for the data and
> squashes a persistent bug. I will follow up with @Jyothis-DCActionhttps://github.com/Jyothis-DCActionabout that variable, I'm pretty sure I'm calculating it incorrectly.
> Waiting on @pdarche https://github.com/pdarche to run a Ruby script for
> me so I can update it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nickmcclellan/dcaction/issues/78#issuecomment-42910930
> .

## 

Peter Darche
(415) 595-2940
