### ISSUE TITLE
Create infocard interaction for point-based visualization

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#8]
While the 1.0 e-Databook populated the sidebar with information for neighborhoods as the user rolled over, we'd like the sidebar information for point based data to allow multiple schools/child care centers to be compared. 

When the user rolls over the points, it will populate the sidebar with information about that school or child care center. However, if they click, they will collect info cards from multiple points, however many they click, so they may compare multiple schools.

This interaction is partly working on the D3 skeleton now, although not all data points are being called into the infocards and the design is not especially elegant.

**Comment by ajschumacher** [comment]
There is now a function "displaySchoolData" in visualization.js which is where this could be done. Right now it's just writing raw html; it could be done in some more clever way if somebody wants to get all mvc on it, but I don't know if we need that much engineering on this one.

**Comment by ajschumacher** [comment]
I think this issue is sort of the same as issue #7; closing this one and copying the text to comments of that one.
