### ISSUE TITLE
Indicator source text with final data csv file

### ISSUE THREAD

**Issue by JyothisS** [DCActionforChildren/dcaction#84]
We would like all source and final data to be accessible. But, currently having the final data CSV file (neighborhoods.csv) next to the Source text for each of the indicators may be confusing to people. So we feel the neighborhoods.csv file should not be next to each source text until we come up with how we organize and make available the data.

**Comment by nickmcclellan** [comment]
I added the CSV icon to the footer so it is not included with each source layer as not to confuse users.

**Comment by JyothisS** [comment]
The CSV icon and file still shows up next to each of the source texts for the indicators.

**Comment by nickmcclellan** [comment]
Sorry, a late-night commit I forgot to make has just been made.
