### ISSUE TITLE
Methodology document // feedback needed

### ISSUE THREAD

**Issue by hyesookchung** [DCActionforChildren/dcaction#85]
Simply wanted to post this site as a preliminary draft of what we will be sharing for methodology. I've put an ask out to Max (but Josh and others -- please feel to chime in) a couple of sentences / paragraph re an explanation of the Census Crosswalk and the Zip Code Crosswalk. 

Thanks everyone.

www.dcactionforchildren.org/kids-count/dc-kids-count-data-tools%202.0%20methodology

**Comment by nickmcclellan** [comment]
I've added a note for methodology at the bottom of the page. I think the methodology is sufficient, we can get feedback on phrasing, but I think having a place where you at least place your methodology is a huge step, even if you continue to edit it. I think it's OK to go for launch.

**Comment by nickmcclellan** [comment]
My initial feedback is to correct the URL so it does not have spaces. Maybe www.dcactionforchildren.org/kids-count/dc-kids-count-data-tools-methodology, so there's no spaces and no periods.

**Comment by hyesookchung** [comment]
done!
http://www.dcactionforchildren.org/dc-kids-count-data-tools-methodology

**Comment by hyesookchung** [comment]
the link from the bottom of the page needs to be changed now. thanks so much Nick.

**Comment by hyesookchung** [comment]
Max is sending me additional langugage
