### ISSUE TITLE
Investigate DC Action CMS for integration help

### ISSUE THREAD

**Issue by nickmcclellan** [DCActionforChildren/dcaction#86]
I will look into the DC Action CMS to see if I can comfortably pull off the integration task this weekend.

**Comment by nickmcclellan** [comment]
I've added the Data Tools 2.0 link to the menu bar. I'm pretty sure I can get a slide up as well. Let me know when you'd like the slide in place.

**Comment by hyesookchung** [comment]
GREAT. I'm waiting for green light from council member Grosso's office before I send out the press release. Are we ready to push out even with the other outstanding issues identified?

**Comment by nickmcclellan** [comment]
I think we're ready to go! Anxious to get this out.

**Comment by hyesookchung** [comment]
just double checking -- can we take down the links on our site for now?

**Comment by ShubhaBala** [comment]
And one last thing... ready to go after this though...  I think DataKind's
agreement with DC Action is actually not to have our logo on the map.  But
thanks so much for thinking of us!!!  Could you just remove that, and then
as long as this is the final look that HyeSook signed off on then we're
ready to go!!!!!!!

Get your champagne/sparkling grape juice bottle READY!

On Tue, May 27, 2014 at 12:32 PM, HyeSook Chung notifications@github.comwrote:

> just double checking -- can we take down the links on our site for now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DCActionforChildren/dcaction/issues/86#issuecomment-44300585
> .

## 

_DataKind http://www.datakind.org/_
Shubha Bala
Programs Strategist
shubha@datakind.org

Follow us on Twitter @DataKind https://twitter.com/DataKind
Get involved and stay in touch http://www.datakind.org/getinvolved/!
Join our NYC Meetup http://www.meetup.com/DataKind-NYC/!

**Comment by hyesookchung** [comment]
OK -- ready to send the press release. ....here we go!

**Comment by hyesookchung** [comment]
LOVE the tab nick with the new image~~ thanks so much.

**Comment by hyesookchung** [comment]
NICK -- LOVING all the updates you made and thanks for prioritizing that today. thanks so much! a lot to celebrate for sure.
