### ISSUE TITLE
Image /Icon for carousel on dcactionforchildren.org

### ISSUE THREAD

**Issue by hyesookchung** [DCActionforChildren/dcaction#87]
Hi guys -- I'm going to reach out to ensure we get a image / icon for the website to be used as a button and on the carousel as a "new" data tool 2.0.

**Comment by hyesookchung** [comment]
confirmed with Emily and she recommended a 'new' image and can create something for us.

**Comment by hyesookchung** [comment]
look who joined! Emily! yea! we are so darn close I want to celebrate!

**Comment by hyesookchung** [comment]
Emily JUST posted. thanks a million!!!

**Comment by nickmcclellan** [comment]
One thing we need is a Google Analytics code to embed into the graphic so we can track visits. HyeSook, is this something you can do? If I'm added to your analytics account I could do it, but maybe it's something your web folks can produce quickly for me. The code will look something like this:

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-105064-1']);
  _gaq.push(['_setDomainName', 'macrumors.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

**Comment by hyesookchung** [comment]
On it -- look into it and forward whatever we have.

**Comment by hyesookchung** [comment]
nick -- just emailed you our account information via email.

**Comment by nickmcclellan** [comment]
Just added it! Now tracking under a new property, Data Tools 2.0.
