### ISSUE TITLE
Add CNAME record to DNS Zone files

### ISSUE THREAD

**Issue by pdarche** [DCActionforChildren/dcaction#89]
add CNAME records to dcactionforchildren.org and dckids.org to point datatools. subdomain to the application hosted on GitHub.

**Comment by pdarche** [comment]
I've added the record to the dcactionforchildren.org and will add it to dckids.org when the settings have propagated and it looks like things are working.

**Comment by pdarche** [comment]
http://datatools.dcactionforchildren.org/ appears to be working (yay!) but GitHub appears to only be able to apply one custom domain to a repo (so datatools.dckids.org isn't working - boo.)  I'm looking into workarounds, but just wanted to update

**Comment by nickmcclellan** [comment]
Why don't we set up a simple redirect for datatools.dckids.org? Just send it to datatools.dcactionforchildren.org.

**Comment by pdarche** [comment]
Was thinking that.  Will try tomorrow

**Comment by pdarche** [comment]
datatools.dckids.org now redirects to datatools.dcactionforchildren.org
