### ISSUE TITLE
Fix some heights/layout for mobile view

### ISSUE THREAD

**Issue by eschow** [DCActionforChildren/dcaction#91]
The height of the map is way to large for a mobile screen and the panel overlay for each narrative obscures most of the map.

Choose a dataset also expands so far out that it's hard to get back to the map.

**Comment by hyesookchung** [comment]
I was trying to use it on my iPad and it kept crashing and couldn't get it to work. the overlay were on top of the maps on the iPad as we.

**Comment by cmgiven** [comment]
Move discussion to #150.
