### ISSUE TITLE
increase/decrease button is hidden

### ISSUE THREAD

**Issue by hyesookchung** [DCActionforChildren/dcaction#94]
it's hard to access as it's now hidden behind the choose dataset button

**Comment by nickmcclellan** [comment]
I fixed this last week, a recent commit broke it again. I will restore this again.

**Comment by eschow** [comment]
The fix that was implemented was creating a gray transparent bar where the
Maps Terms of Service rectangles were. I removed that CSS fix because of it.

Top: 10px was working on classes being called elsewhere, basically.

**Comment by nickmcclellan** [comment]
Let me see if I can find a middle ground...I did see the terms of service drag, I didn't realize my zoom button fix was responsible.

**Comment by nickmcclellan** [comment]
OK, my latest fix accomplishes both objectives
