### ISSUE TITLE
indicator boxes

### ISSUE THREAD

**Issue by hyesookchung** [DCActionforChildren/dcaction#95]
I'm viewing on my iPad and lap top -- the 1 line sentence can be seen on the iPad but not on the lap top. not sure what's going on . Love the sentence above it.

**Comment by eschow** [comment]
Which 1 line sentence?

I had to tweak when some language is shown or hidden depending on length and screen size.

**Comment by hyesookchung** [comment]
for the children in poverty: Among 25% of the poorest neighborhoods, 1 in 2 children live in poverty.

Students Proficient in Reading: 40% of DC neighborhoods have less than half of their students scoring proficient in reading.

do you see them? I have text for the other two.

**Comment by hyesookchung** [comment]
hey -- I think it's fine without the sentences but it's just that on my iPad it shows up and laptop it doesn't. We can delete them if it's earlier.

**Comment by nickmcclellan** [comment]
I hide the subheads when the viewport prevents them from being seen or if the box becomes too small to accomodate all the text.
