### ISSUE TITLE
Add a link to the old project from new...

### ISSUE THREAD

**Issue by eschow** [DCActionforChildren/dcaction#96]
So that if we replace the link in the nav of dcactionforchildren.org, there's still a place to find the old one.

Open to other solutions for archiving data tool 1.0

**Comment by nickmcclellan** [comment]
I'm happy to add this link, although I think the old data tools page was recently unpublished. The link wasn't working for me.

**Comment by hyesookchung** [comment]
Emily -- just clarifying -- you were thinking of having 1.0 as a link somewhere for folks

**Comment by hyesookchung** [comment]
as a quick and easy solution for now -- I think we under the 1.0 and the methodology tabs can be pulled from the website. We already have a link to the methodology section from 2.0. we'll have to re-organized the tabs once the web-redesign takes place. does that work?
