### ISSUE TITLE
Legend issues when fewer than 5 choropleth classes

### ISSUE THREAD

**Issue by denglend** [DCActionforChildren/dcaction#97]
Love the tool.  Happy to submit a pull request for this issue if you prefer.  Here's the story:

When using the library, grocery, or rec center data sets to color the map, there is one more color class used on the map than is present in the legend.  The displayed legend colors may or may not match correctly with the colors displayed on the map.

For example, when using the rec center data set, the legend has four entries: 
- 1 and below
- 1 - 2
- 2 - 3
- Above 4

While the map has all five color classes showing, and Georgetown, for instance, matches the legend color for "Above 4", but it only has 3 rec centers.

I didn't check thoroughly, but it looks like a couple of things might be going on, the first of which is that you're using _.compact on the data_values in changeNeighborhoodData.  compact filters out all false-ish values, which includes 0, so all zeroes are removed from the data.  I'm guessing you're using _.compact to get ride of undefineds, nulls, etc.  If so, you could replace with a .filter with isNaN instead, so you keep the zeroes.  

Even after this change, I think there might still be some strange behavior with the logic later in the function, stemming from the way you've written the legend text ("1 and below") and the way threshold scales work in d3 (input values exactly on a threshold are mapped to the higher of the two range output values that the threshold borders).

I think the easiest solution is checking if the number of unique values is 5 or less, and if so, skipping all the jenks and threshold logic and setting choro_color to a simple mapping function instead.  Side-note: this would also allow you to add non-numeric data at a future date, if you wanted to (e.g. Candidate voted for in the election).

**Comment by andylolz** [comment]
Ooh – great stuff, @denglend!

> compact filters out all false-ish values, which includes 0, so all zeroes are removed from the data

V good point! `filter ... !isNaN` does indeed do the trick!

> (input values exactly on a threshold are mapped to the higher of the two range output values that the threshold borders)

Good point again. Rewording fixes this one.

> …skipping all the jenks and threshold logic and setting choro_color to a simple mapping function instead

Hmm… Nice feature, but I haven’t implemented this one.

PR on its way!

**Comment by cmgiven** [comment]
Closed with #112.
